bookstore/Controllers/ShoppingEventController.cs
using bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bookstore.Controllers
{
    public class ShoppingEventController : Controller
    {
        private IShoppingEventRepository repo { get; set; }

        private Cart cart { get; set; }

        public ShoppingEventController(IShoppingEventRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }



        //create checkout event for get and post

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new ShoppingEvent());
        }


        [HttpPost]

        public IActionResult Checkout(ShoppingEvent shoppingEvent)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty");
            }

            if (ModelState.IsValid)
            {
                shoppingEvent.Lines = cart.Items.ToArray();
                repo.SaveShoppingEvent(shoppingEvent);
                cart.ClearCart();

                return RedirectToPage("/CheckoutCompleted");
            }
            else
            {
                return View();
            }
        }
    }
}

bookstore/Pages/CheckoutCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace bookstore.Pages
{
    public class CheckoutCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

bookstore/Pages/Shop.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bookstore.Infrastructure;
using bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace bookstore.Pages
{
    public class ShopModel : PageModel
    {
        public IBookstoreRepository repo { get; set; }


        //create cart object
        public Cart cart { get; set; }

        public ShopModel (IBookstoreRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }



        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        //create post method with json session
        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);


            cart.AddItem(b, 1);


            //add return url segment
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        //add onpost remove

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            cart.RemoveItem(cart.Items.First(x => x.Book.BookId == bookId).Book);
            return RedirectToPage(new {ReturnUrl = returnUrl});
        }
    }
}

bookstore/Pages/CheckoutCompleted.cshtml
@page
@model bookstore.Pages.CheckoutCompletedModel
@{
}

<!-- add a thank you for shopping page-->

<div class="text-center">
    <h2>Thanks for shopping!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

bookstore/Pages/Shop.cshtml
@page
@model bookstore.Pages.ShopModel
@{
}

<h2>Your cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>


    </thead>

    <tbody>
        @foreach(var i in Model.cart.Items)
            {
                <tr>
                    <td>@i.Book.Title</td>
                    <td>@i.Quantity</td>
                    <td>@i.Book.Price</td>
                    <td>@(i.Quantity * i.Book.Price)</td>

                    <!-- add remove form-->
                    <td class="text-center">
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="bookId" value="@i.Book.BookId" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">Remove</button>

                        </form>
                    </td>


                </tr>
            }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.cart.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>




</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Keep Shopping</a>
    <a class="btn btn-primary" asp-controller="ShoppingEvent" asp-action="Checkout">Checkout</a>
</div>

bookstore/Pages/_ShopLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.css" rel="stylesheet" />

</head>
<body>

    <div class="bg-dark text-white p-2">
        MyBookstore
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>